[package]
name = "kapitan-dupa-the-game"
version = "0.1.0"
authors = ["cvgore <kacper@cvgo.re>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3"